version: '3.8'

services:
  minisql:
    build: .
    container_name: minisql
    stdin_open: true
    tty: true
    volumes:
      - ./data:/app/data
    working_dir: /app/bin
    restart: unless-stopped